//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTechnology.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        public string MaBaiViet { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayDang { get; set; }
        public string MaKhachHang { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
